name       : xdo
version    : 0.5.3
release    : 1
source     :
    - https://github.com/baskerville/xdo/archive/0.5.3.tar.gz : fd63f2bbd1bd4a8838778b65046e2458e81dd2beb36a38aca47d852084d29376
license    : BSD-2-Clause
component  : system.utils
summary    : Small X utility to perform elementary actions on windows
description: |
    Small X utility to perform elementary actions on windows
builddeps  :
    - pkgconfig(xcb-icccm)
build      : |
    %make PREFIX=/usr
install    : |
    %make_install PREFIX=/usr
