name       : xdo
version    : 0.5.7
release    : 2
source     :
    - https://github.com/baskerville/xdo/archive/0.5.7.tar.gz : b661229f0457939d3867cca1664c5671ae959b309feb58abe9142229c8c7ffb4
license    : BSD-2-Clause
component  : system.utils
summary    : Small X utility to perform elementary actions on windows
description: |
    Small X utility to perform elementary actions on windows
builddeps  :
    - pkgconfig(xcb-aux)
    - pkgconfig(xcb-icccm)
build      : |
    %make PREFIX=/usr
install    : |
    %make_install PREFIX=/usr
